// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPuua2v8xKVyZMs7NPkl8iARmTxK24ZY',
    appId: '1:402203194554:web:223fe4e40dc4250b32be83',
    messagingSenderId: '402203194554',
    projectId: 'login-app-8a782',
    authDomain: 'login-app-8a782.firebaseapp.com',
    storageBucket: 'login-app-8a782.appspot.com',
    measurementId: 'G-Y8B1PSN6ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCFyuxyPfV_9bl4SYXixNFoJoZb2BkyrA',
    appId: '1:402203194554:android:a8d75cb9f7f9889032be83',
    messagingSenderId: '402203194554',
    projectId: 'login-app-8a782',
    storageBucket: 'login-app-8a782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3TLZV9hXQDE0iEfjTr4SJ7aWh0I6FIX4',
    appId: '1:402203194554:ios:b2408c5c2ec3de7732be83',
    messagingSenderId: '402203194554',
    projectId: 'login-app-8a782',
    storageBucket: 'login-app-8a782.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3TLZV9hXQDE0iEfjTr4SJ7aWh0I6FIX4',
    appId: '1:402203194554:ios:b2408c5c2ec3de7732be83',
    messagingSenderId: '402203194554',
    projectId: 'login-app-8a782',
    storageBucket: 'login-app-8a782.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWPuua2v8xKVyZMs7NPkl8iARmTxK24ZY',
    appId: '1:402203194554:web:45858591c5bb39a232be83',
    messagingSenderId: '402203194554',
    projectId: 'login-app-8a782',
    authDomain: 'login-app-8a782.firebaseapp.com',
    storageBucket: 'login-app-8a782.appspot.com',
    measurementId: 'G-2VY5N4H43J',
  );

}